src/Feature/Blogs/code/Models/ArticleModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlogWebsiteHelix.Feaure.Blogs.Models
{
    public class ArticleModel 
    {
        public virtual string Id { get; set; }
        public virtual string ItemName { get; set; }
        public virtual string Title { get; set; }
        public virtual string ShortDescription { get; set; }
        public virtual string LongDescription { get; set; }
        public virtual string ArticleSmallImage { get; set; }
        public virtual string ArticleLargeImage { get; set; }
        public virtual DateTime PostedDate { get; set; }
        public virtual string Category { get; set; }
        public virtual List<string> Tags { get; set; }
        public virtual string Author { get; set; }
    }
}

src/Feature/Blogs/code/Models/SearchModel.cs
using Sitecore.ContentSearch;
using Sitecore.ContentSearch.SearchTypes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlogWebsiteHelix.Feaure.Blogs.Models
{
    public class SearchModel : SearchResultItem
    {
        [IndexField("_name")]
        public virtual string ItemName { get; set; }

        [IndexField("author_t")]
        public virtual string Author { get; set; }

        [IndexField("description_t")]
        public virtual string Description { get; set; } // Custom field on my template

        [IndexField("title_t")]
        public virtual string Title { get; set; } // Custom field on my template
    }

    public class SearchResult
    {
        public string ItemName { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Description { get; set; }
    }

    /// <summary>
    /// Custom search result model for binding to front end
    /// </summary>
    public class SearchResults
    {
        public List<SearchResult> Results { get; set; }
    }
}

src/Feature/Blogs/code/Controllers/BlogPostcardSearchController.cs
using BlogWebsiteHelix.Feaure.Blogs.Models;
using Sitecore.ContentSearch;
using Sitecore.ContentSearch.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogWebsiteHelix.Feaure.Blogs.Controllers
{
    public class BlogPostcardSearchController : Controller
    {
        // GET: BlogPostcardSearch

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DoSearch(string searchText)
        {
            var myResults = new SearchResults
            {
                Results = new List<SearchResult>()
            };
            var searchIndex = ContentSearchManager.GetIndex("sitecore_web_index"); // Get the search index
            //var searchPredicate = GetSearchPredicate(searchText); // Build the search predicate
            using (var searchContext = searchIndex.CreateSearchContext()) // Get a context of the search index
            {
                //Select * from Sitecore_web_index Where Author="searchText" OR Description="searchText" OR Title="searchText"
                //var searchResults = searchContext.GetQueryable<SearchModel>().Where(searchPredicate); // Search the index for items which match the predicate
                var searchResults = searchContext.GetQueryable<SearchModel>()
                    .Where(x => x.Author.Contains(searchText) || x.Title.Contains(searchText) || x.Description.Contains(searchText));   //LINQ query

                var fullResults = searchResults.GetResults();

                // This is better and will get paged results - page 1 with 10 results per page
                //var pagedResults = searchResults.Page(1, 10).GetResults();
                foreach (var hit in fullResults.Hits)
                {
                    myResults.Results.Add(new SearchResult
                    {
                        Description = hit.Document.Description,
                        Title = hit.Document.Title,
                        ItemName = hit.Document.ItemName,
                        Author = hit.Document.Author
                    });
                }
                return new JsonResult { JsonRequestBehavior = JsonRequestBehavior.AllowGet, Data = myResults };
            }

        }
    }
}

src/Feature/Blogs/code/Controllers/SitecoreBlogPostcardController.cs
using BlogWebsiteHelix.Feaure.Blogs.Models;
using Sitecore.Web.UI.WebControls;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogWebsiteHelix.Feaure.Blogs.Controllers
{
    public class SitecoreBlogPostcardController : Controller
    {
        // GET: SitecoreBlogPostcard
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetPostcard()
        {

            var result = new List<ArticleModel>();
            try
            {
                Sitecore.Data.Database database = Sitecore.Configuration.Factory.GetDatabase("web");
                Sitecore.Data.Items.Item[] allItems = database.SelectItems(@"fast:/sitecore/content/BlogWebsite/Articles//*[@@templateid='{DF55902C-D8C5-4167-AB23-C53F1EC5DC40}']");

                foreach (var item in allItems)
                {
                    Sitecore.Data.Fields.ReferenceField dl = item.Fields["Category"];
                    string str = dl != null && dl.TargetItem != null ? dl.TargetItem.Name : "";
                    result.Add(new ArticleModel
                    {
                        Id = FieldRenderer.Render(item, "Id"),
                        Title = FieldRenderer.Render(item, "Title"),
                        ShortDescription = FieldRenderer.Render(item, "ShortDescription"),
                        LongDescription = FieldRenderer.Render(item, "LongDescription"),
                        ArticleSmallImage = FieldRenderer.Render(item, "ArticleSmallImage"),
                        PostedDate = Convert.ToDateTime(FieldRenderer.Render(item, "PostedDate")),
                        Author = FieldRenderer.Render(item, "Author"),
                        Category = str//FieldRenderer.Render(item, "Category"),
                    });
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

            //return new JsonResult { JsonRequestBehavior = JsonRequestBehavior.AllowGet, Data = result };
            //var items = Sitecore.Context.Database.SelectItems("{56741DF6-7290-4E29-B0D1-11A05EE63AFF}");

            return View("~/Views/BlogWebsiteHelix/Postcard.cshtml", result);
        }

        public ActionResult GetBlogDetail(string blogId)
        {
            ViewBag.blogId = blogId;
            var result = new ArticleModel();
            try
            {

                var item = Sitecore.Context.Database.GetItem(blogId);
                Sitecore.Data.Fields.ReferenceField dl = item.Fields["Category"];
                string str = dl != null && dl.TargetItem != null ? dl.TargetItem.Name : "";
                List<string> tags = new List<string>();
                Sitecore.Data.Fields.MultilistField multilistField = item.Fields["Tags"];
                if (multilistField != null)
                {
                    foreach (Sitecore.Data.Items.Item tag in multilistField.GetItems())
                    {
                        tags.Add(tag.Name);
                    }
                }
                result = new ArticleModel
                {
                    Id = FieldRenderer.Render(item, "Id"),
                    Title = FieldRenderer.Render(item, "Title"),
                    ItemName = FieldRenderer.Render(item, "ItemName"),
                    LongDescription = FieldRenderer.Render(item, "LargeDescription"),
                    ArticleLargeImage = FieldRenderer.Render(item, "ArticleLargeImage"),
                    PostedDate = Convert.ToDateTime(FieldRenderer.Render(item, "PostedDate")),
                    Author = FieldRenderer.Render(item, "Author"),
                    Category = str,//FieldRenderer.Render(item, "Category"),
                    Tags = tags
                };
            }
            catch (Exception ex)
            {
                throw;
            }
            return View("~/Views/BlogWebsiteHelix/blog-detail.cshtml", result);
        }
    }
}

src/Feature/Blogs/code/Views/BlogWebsiteHelix/Footer.cshtml
<div>
    @{
        //var item = Sitecore.Context.Database.GetItem("/sitecore/content/Alexa/LocalSettings");
        var item = Sitecore.Context.Database.GetItem("{6D558108-FC5E-4A19-AE7A-D4AFC8B91879}");
    }

</div>

<div class="container">
	  <div class="text-white bg-primary">
		<p class="lead">@Html.Raw(item.Fields["Copyright"].Value)</p>
	  </div>
</div>
	  

src/Feature/Blogs/code/Views/BlogWebsiteHelix/Header.cshtml
<div>
    @{
        //var item = Sitecore.Context.Database.GetItem("/sitecore/content/Alexa/LocalSettings");
        var item = Sitecore.Context.Database.GetItem("{6D558108-FC5E-4A19-AE7A-D4AFC8B91879}");
    }

</div>

@*<div>
        <h1>@Html.Raw(item.Fields["Header-Title"].Value)</h1><br />
        @Html.Raw(item.Fields["Header-SubTitle"].Value)
    </div>*@
<div class="container">
    <div class="jumbotron text-white bg-primary">
        <h1 class="display-3">@Html.Raw(item.Fields["Header-Title"].Value)</h1>
        <p class="lead"> @Html.Raw(item.Fields["Header-SubTitle"].Value)</p>
    </div>
</div><!-- /.container -->

src/Feature/Blogs/code/Views/BlogWebsiteHelix/MasterLayout.cshtml
@using Sitecore.Mvc
@using Sitecore.Mvc.Analytics.Extensions
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en" xmlns="https://www.w3.org/1999/xhtml">

<head>
    <link href="~/assets/css/blogsite.css" rel="stylesheet" />
    <link href="~/assets/css/bootstrap-themed.min.css" rel="stylesheet" />
</head>


<body>
    <div>
        @Html.Sitecore().Placeholder("phMain")
    </div>
</body>
</html>

src/Feature/Blogs/code/Views/BlogWebsiteHelix/PageBody.cshtml
@{
    //var item = Sitecore.Context.Database.GetItem("/sitecore/content/Alexa/LocalSettings");
    var item = Sitecore.Context.Database.GetItem("{A8DDBE42-DEB3-46C3-A70F-4092BB4BB653}");
}

<div class="container">
    <div class="jumbotron text-white bg-primary">
        <h1 class="display-3">@Html.Raw(item.Fields["Title"].Value)</h1>
        <p class="lead"> @Html.Raw(item.Fields["Description"].Value)</p>
    </div>
</div>

src/Feature/Blogs/code/Views/BlogWebsiteHelix/Postcard.cshtml
@using System.Web.Mvc;
@model IEnumerable<BlogWebsiteHelix.Feaure.Blogs.Models.ArticleModel>
@{
    var item = Sitecore.Context.Database.GetItem("{6D558108-FC5E-4A19-AE7A-D4AFC8B91879}");
}
<main class="container blog-posts">
    @if (Model != null)
    {
        <div class="row">

            @foreach (var card in Model)
            {
            <div class="blog-post-card card col-lg-4 col-md-6">
                @Html.Raw(card.ArticleSmallImage)
                <div class="card-body bg-light">
                    <strong class="d-inline-block mb-2 text-success">Design</strong>
                    <h3 class="card-title">@Html.Raw(card.Title)</h3>
                    <div class="mb-1 text-muted">@Html.Raw(card.PostedDate.ToString("MMM dd, yyyy"))</div>
                    <p>@Html.Raw(card.ShortDescription)</p>
                    <a class="btn btn-warning btn-block" href="/blogdetail?blogId=@Html.Raw(card.Id)">@Html.Sitecore().Field("PostCardButtonText", item)</a>
                </div>
            </div>
            }
        </div>
    }
</main>

@*<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script>
	$(document).ready(function () {
        function onclickFunction(Id) {
            $.ajax({
             type: "Post",
                datatype: "JSON", url: "@Url.Action("GetBlogDetail", "SitecoreBlogPostcardController")",
                contentType: "application/json",
                data: {
                    blogId: Id
                },
                success: function (data) {
                   
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('error');
                }
            });
            return false;
        }

</script>*@

src/Feature/Blogs/code/Views/BlogWebsiteHelix/Search.cshtml
@{
    var item = Sitecore.Context.Database.GetItem("{6D558108-FC5E-4A19-AE7A-D4AFC8B91879}");
}

<div class="col-sm-12">
    <div class="form-group">
        <div class="main-search">
            <div class="input-group input-group pl-4 pr-4">
                <input type="text" class="form-control" id="searchInput" placeholder="@Html.Raw(item.Fields["HighlightedText"].Value)">
                <div class="input-group-append">
                    <button type="button" class="btn btn-dark" id="searchButton">@Html.Raw(item.Fields["ButtonLabel"].Value)</button>
                </div>
            </div>
        </div>
        <div id="resultsItem" class="text-white"></div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script>
		$(document).ready(function () {
			$("#searchButton").click(function (e) {
				// debugger;
				e.preventDefault();
                if ($('#searchInput').val() == '' || $('#searchInput').val() == undefined) {
					$('#resultsItem').text("Please enter some text first.").addClass('text-danger');
                    return false;
                }
				$.ajax({
					type: "GET",
					datatype: "JSON", url: "@Url.Action("DoSearch", "BlogPostcardSearch")",
					contentType: "application/json",
					data: {
						searchText: $("#searchInput").val()
					},
					success: function (result) {
						var resultText = "";
						$('#resultsItem').text(resultText);
						$('#resultsItem').append("Results from SOLR index <BR><BR>");
						$(result.Results).each(function (index, item) {
							// each iteration
							var Description = item.Description;
							var Title = item.Title;
							var Author = item.Author;
							var ItemName = item.ItemName;
							resultText += (index + 1) + " - " + ItemName + Title + "; " + Author + "; " + Description + "; " + "<BR><BR>";
						});
						$('#resultsItem').append(resultText);
					},
					error: function (result) {
						alert('error');
					}
				});
			});
		});
</script>

src/Feature/Blogs/code/Views/BlogWebsiteHelix/blog-detail.cshtml
@model BlogWebsiteHelix.Feaure.Blogs.Models.ArticleModel
@{
    var blogId = ViewBag.blogId;
    var item = Sitecore.Context.Database.GetItem(blogId);
}
<main role="main" class="container blog-post-detail">
    <div class="row">
        <div class="col-lg-12">
            <div class="blog-post-detail-card card">
                <img src="~/assets/images/tech.jpg" />               
                <div class="card-body bg-light">
                    <strong class="d-inline-block mb-2 text-success">Design</strong>
                    <h3 class="card-title">@Html.Raw(item.Fields["Title"].Value)</h3>
                    <div class="mb-1 text-muted">@Html.Raw(Model.PostedDate.ToString("MMM dd, yyyy"))</div>
                    @Html.Raw(item.Fields["LongDescription"].Value)
                    <p></p>
                    <div class="blog-detail-tag-list">
                        <span class="read-more-heading">Read more: </span>
                        @*@if (Model.Tags)
                {
                    foreach (var str in Model.Tags)
                    {
                        <a class="btn btn-info" href="#" role="button">@str</a>
                    }
                }*@
                        <a class="btn btn-info" href="#" role="button">Tag</a>
                        <a class="btn btn-info" href="#" role="button">Super Extra Long Tag</a>
                        <a class="btn btn-info" href="#" role="button">Extra Long Tag</a>


                    </div>
                </div>
            </div>
        </div>
    </div>
</main>